apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.17.0
    chart: external-secrets
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false